

services:

  bookreader:
    container_name: bookreader
    image: lipanski/docker-static-website:latest
    command: ["/busybox-httpd", "-f", "-v", "-p", "3000"]
    volumes:
      - ./apps/bookreader:/home/static
      - ./apps/libs:/home/static/libs
    ports:
      - "8091:3000"


  dashboard:
    container_name: dashboard
    image: lipanski/docker-static-website:latest
    command: ["/busybox-httpd", "-f", "-v", "-p", "3000"]
    volumes:
      - ./apps/dashboard:/home/static
      - ./apps/libs:/home/static/libs
    ports:
      - "8092:3000"



  server:
    image: ghcr.io/muchobien/pocketbase:0.25.1
    container_name: server
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./server/pb_data:/pb_data
      - ./server/pb_migrations:/pb_migrations
      - ./server/pb_hooks:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
